/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSummarizeRouteImport } from './routes/_layout.summarize'
import { Route as LayoutPlannerRouteImport } from './routes/_layout.planner'
import { Route as LayoutEmailRouteImport } from './routes/_layout.email'
import { Route as LayoutChatRouteImport } from './routes/_layout.chat'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSummarizeRoute = LayoutSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlannerRoute = LayoutPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailRoute = LayoutEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/chat': typeof LayoutChatRoute
  '/email': typeof LayoutEmailRoute
  '/planner': typeof LayoutPlannerRoute
  '/summarize': typeof LayoutSummarizeRoute
}
export interface FileRoutesByTo {
  '/chat': typeof LayoutChatRoute
  '/email': typeof LayoutEmailRoute
  '/planner': typeof LayoutPlannerRoute
  '/summarize': typeof LayoutSummarizeRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/email': typeof LayoutEmailRoute
  '/_layout/planner': typeof LayoutPlannerRoute
  '/_layout/summarize': typeof LayoutSummarizeRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/email' | '/planner' | '/summarize'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat' | '/email' | '/planner' | '/summarize' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/chat'
    | '/_layout/email'
    | '/_layout/planner'
    | '/_layout/summarize'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/summarize': {
      id: '/_layout/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof LayoutSummarizeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/planner': {
      id: '/_layout/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof LayoutPlannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email': {
      id: '/_layout/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof LayoutEmailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutEmailRoute: typeof LayoutEmailRoute
  LayoutPlannerRoute: typeof LayoutPlannerRoute
  LayoutSummarizeRoute: typeof LayoutSummarizeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutEmailRoute: LayoutEmailRoute,
  LayoutPlannerRoute: LayoutPlannerRoute,
  LayoutSummarizeRoute: LayoutSummarizeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
